apiVersion: apps/v1
kind: Deployment
metadata:
  name: fingerprints
  labels:
    app: fingerprints
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fingerprints
  template:
    metadata:
      labels:
        app: fingerprints
    spec:
      containers:
        - name: fingerprints
          image: fingerprints/prueba
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: fingerprints
spec:
  selector:
    app: fingerprints
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer